using System;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using Unity.AI.Navigation;
using Object=UnityEngine.Object;
namespace BlackMarket.Editor {
 public static class ArmoryRevisionBuilder {
  const string R="Assets/BlackMarket/",A=R+"Art/ArmoryRevision/";static Transform root;static Material steel,wall,floor,glass,wood,white,screen,red;
  [MenuItem("BLACK MARKET/Rebuild Map 2 and desktop computers")]
  public static void Build(){Directory.CreateDirectory(A+"Materials");AssetDatabase.Refresh();
   steel=Mat("Graphite",new Color(.12f,.16f,.18f));wall=Mat("Concrete",new Color(.39f,.44f,.46f));floor=Mat("Floor",new Color(.25f,.31f,.34f));var floorSource=AssetDatabase.LoadAssetAtPath<Material>(R+"Resources/Materials/concrete_floor_02.mat");if(floorSource){floor.CopyPropertiesFromMaterial(floorSource);floor.mainTextureScale=new Vector2(15,20);}
   wood=Mat("Desk",new Color(.38f,.25f,.15f));white=Mat("Ivory",new Color(.8f,.85f,.83f));red=Mat("Medical red",new Color(.7f,.06f,.035f));screen=Mat("Monitor light",new Color(.025f,.23f,.32f));screen.EnableKeyword("_EMISSION");screen.SetColor("_EmissionColor",new Color(.04f,.35f,.5f));
   glass=Mat("Safety glass",new Color(.35f,.72f,.78f,.17f));glass.SetFloat("_Surface",1);glass.SetFloat("_SrcBlend",5);glass.SetFloat("_DstBlend",10);glass.SetFloat("_ZWrite",0);glass.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");glass.renderQueue=3000;
   ImportSources();BuildGun("AK47","AK",1.0f);BuildGun("M700","Sniper",1.15f);BuildDesktop();BuildChair();BuildMap();AssetDatabase.SaveAssets();EditorSceneManager.OpenScene(R+"Scenes/NorthPoint.unity");Debug.Log("ARMORY REVISION BUILD COMPLETE");
  }
  public static void PatchWeaponGrips(){foreach(var id in new[]{"AK","Sniper"}){string path=R+"Resources/Actors/"+id+".prefab";var o=PrefabUtility.LoadPrefabContents(path);o.transform.Find("Right grip").localPosition=new Vector3(.025f,.055f,.10f);o.transform.Find("Left grip").localPosition=new Vector3(0,.11f,.38f);o.transform.Find("Stock").localPosition=new Vector3(0,.12f,-.25f);PrefabUtility.SaveAsPrefabAsset(o,path);PrefabUtility.UnloadPrefabContents(o);}AssetDatabase.SaveAssets();}
  static Material Mat(string name,Color c){string path=A+"Materials/"+name+".mat";var m=AssetDatabase.LoadAssetAtPath<Material>(path);if(!m){m=new Material(Shader.Find("Universal Render Pipeline/Lit"));AssetDatabase.CreateAsset(m,path);}m.color=c;m.SetFloat("_Smoothness",.35f);return m;}
  static GameObject Box(string n,Vector3 p,Vector3 s,Material m,bool solid=true,Transform parent=null){var o=GameObject.CreatePrimitive(PrimitiveType.Cube);o.name=n;o.transform.SetParent(parent?parent:root,false);o.transform.localPosition=p;o.transform.localScale=s;o.GetComponent<Renderer>().sharedMaterial=m;if(!solid)Object.DestroyImmediate(o.GetComponent<Collider>());return o;}
  static Transform Node(string n,Vector3 p,Transform parent=null){var o=new GameObject(n);o.transform.SetParent(parent?parent:root,false);o.transform.localPosition=p;return o.transform;}
  static void Marker(string id,Vector3 p){Node(id,p).gameObject.AddComponent<WorldMarker>().id=id;}
  static void Point(string id,string title,Vector3 p){var i=Node(title,p).gameObject.AddComponent<Interaction>();i.id=id;i.title=title;}
  static void Sign(string label,Vector3 p,float yaw=180){var t=Node(label,p);t.rotation=Quaternion.Euler(0,yaw,0);var m=t.gameObject.AddComponent<TextMesh>();m.text=label;m.font=Resources.Load<Font>("Fonts/Bold");m.fontSize=64;m.characterSize=.055f;m.anchor=TextAnchor.MiddleCenter;m.color=Color.white;t.GetComponent<Renderer>().sharedMaterial=m.font.material;t.gameObject.AddComponent<WorldTextDepth>();}
  static Bounds BoundsOf(GameObject o){var rr=o.GetComponentsInChildren<Renderer>();var b=rr[0].bounds;foreach(var r in rr)b.Encapsulate(r.bounds);return b;}
  static void ImportSources(){foreach(var path in Directory.GetFiles(A+"Sources","*.png",SearchOption.AllDirectories)){var ti=AssetImporter.GetAtPath(path) as TextureImporter;if(!ti)continue;ti.maxTextureSize=1024;if(path.Contains("nor_gl")||path.EndsWith("_N.png"))ti.textureType=TextureImporterType.NormalMap;ti.SaveAndReimport();}
   foreach(var f in Directory.GetFiles(A+"Sources","*.fbx",SearchOption.AllDirectories)){var mi=AssetImporter.GetAtPath(f) as ModelImporter;if(mi){mi.isReadable=true;mi.importAnimation=false;mi.SaveAndReimport();}}
  }
  static Material SourceMaterial(string name,string diff,string normal){var m=Mat(name,Color.white);m.mainTexture=AssetDatabase.LoadAssetAtPath<Texture2D>(diff);if(File.Exists(normal)){m.SetTexture("_BumpMap",AssetDatabase.LoadAssetAtPath<Texture2D>(normal));m.EnableKeyword("_NORMALMAP");}return m;}
  static GameObject Prop(string path,Vector3 pos,float size,float yaw=0){var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(path);if(!prefab)throw new Exception("Missing "+path);var holder=Node(prefab.name,Vector3.zero);var o=Object.Instantiate(prefab,holder);o.transform.localPosition=Vector3.zero;foreach(var c in o.GetComponentsInChildren<Collider>())Object.DestroyImmediate(c);foreach(var i in o.GetComponentsInChildren<Interaction>())Object.DestroyImmediate(i);var b=BoundsOf(o);float scale=size/Mathf.Max(b.size.x,b.size.y,b.size.z);o.transform.localScale*=scale;b=BoundsOf(o);o.transform.position-=new Vector3(b.center.x,b.min.y,b.center.z);holder.SetPositionAndRotation(pos,Quaternion.Euler(0,yaw,0));return holder.gameObject;}
  static void Scan(string name,Vector3 pos,float size,float yaw=0){string d=A+"Sources/"+name+"/";var o=Prop(d+name+"_1k.fbx",pos,size,yaw);foreach(var r in o.GetComponentsInChildren<Renderer>()){var mats=r.sharedMaterials;for(int i=0;i<mats.Length;i++){string suffix=name=="potted_plant_02"?(mats[i].name.ToLower().Contains("lea")?"_leaves":"_pot"):"";mats[i]=SourceMaterial(name+suffix,d+name+suffix+"_diff_1k.png",d+name+suffix+"_nor_gl_1k.png");if(suffix=="_leaves"){mats[i].SetFloat("_Cull",0);}}r.sharedMaterials=mats;}}
  static void BuildGun(string source,string id,float length){var holder=new GameObject(id);root=holder.transform;string d=A+"Sources/SteinWeapons/WeaponsPack/"+source+"/";var src=Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(d+"SKM_"+source+".fbx"),root);src.name="Imported CC0 "+source;var b=BoundsOf(src);Debug.Log(source+" native bounds "+b);if(b.size.x>b.size.z)src.transform.rotation=Quaternion.Euler(0,-90,0);b=BoundsOf(src);src.transform.localScale*=length/Mathf.Max(b.size.x,b.size.y,b.size.z);b=BoundsOf(src);src.transform.position-=b.center;src.transform.position+=new Vector3(0,.045f,.23f);var mat=SourceMaterial(source,d+"T_"+source+"_C.png",d+"T_"+source+"_N.png");foreach(var r in src.GetComponentsInChildren<Renderer>())r.sharedMaterials=r.sharedMaterials.Select(x=>mat).ToArray();foreach(var c in src.GetComponentsInChildren<Collider>())Object.DestroyImmediate(c);
   foreach(var skin in src.GetComponentsInChildren<SkinnedMeshRenderer>()){var mesh=new Mesh();skin.BakeMesh(mesh);Debug.Log(source+" mesh vertices "+mesh.vertexCount);string mp=A+source+"_"+skin.name+".asset";var oldMesh=AssetDatabase.LoadAssetAtPath<Mesh>(mp);if(oldMesh){EditorUtility.CopySerialized(mesh,oldMesh);Object.DestroyImmediate(mesh);mesh=oldMesh;}else AssetDatabase.CreateAsset(mesh,mp);var obj=skin.gameObject;var materials=skin.sharedMaterials;Object.DestroyImmediate(skin);obj.AddComponent<MeshFilter>().sharedMesh=mesh;obj.AddComponent<MeshRenderer>().sharedMaterials=materials;}

   b=BoundsOf(src);src.transform.localScale*=length/Mathf.Max(b.size.x,b.size.y,b.size.z);b=BoundsOf(src);src.transform.position+=new Vector3(0,.045f,.23f)-b.center;Debug.Log(id+" final size "+BoundsOf(src).size);
   Node("Right grip",new Vector3(.025f,.055f,.10f));Node("Left grip",new Vector3(0,.11f,.38f));Node("Stock",new Vector3(0,.12f,-.25f));Node("Muzzle",new Vector3(0,.05f,.23f+length*.5f));
   if(id=="Sniper"){var scope=GameObject.CreatePrimitive(PrimitiveType.Cylinder);scope.name="Ống ngắm quang học";scope.transform.SetParent(root,false);scope.transform.localPosition=new Vector3(0,.15f,.1f);scope.transform.localRotation=Quaternion.Euler(90,0,0);scope.transform.localScale=new Vector3(.065f,.18f,.065f);scope.GetComponent<Renderer>().sharedMaterial=steel;Object.DestroyImmediate(scope.GetComponent<Collider>());}
   PrefabUtility.SaveAsPrefabAsset(holder,R+"Resources/Actors/"+id+".prefab");Object.DestroyImmediate(holder);
  }
  static void BuildDesktop(){var o=new GameObject("Desktop computer - front is +Z");root=o.transform;
   var display=Mat("Desktop display",Color.white);display.mainTexture=AssetDatabase.LoadAssetAtPath<Texture2D>(A+"desktop.png");display.EnableKeyword("_EMISSION");display.SetTexture("_EmissionMap",display.mainTexture);display.SetColor("_EmissionColor",Color.white*.65f);
   Box("Monitor bezel",new Vector3(0,.36f,-.12f),new Vector3(.62f,.38f,.045f),steel,false);Box("Screen faces operator +Z",new Vector3(0,.36f,-.094f),new Vector3(.57f,.325f,.008f),display,false);Box("Stand",new Vector3(0,.12f,-.12f),new Vector3(.07f,.22f,.07f),steel,false);Box("Base",new Vector3(0,.018f,-.10f),new Vector3(.28f,.03f,.19f),steel,false);
   Box("Keyboard",new Vector3(-.03f,.024f,.20f),new Vector3(.46f,.035f,.16f),steel,false);for(int row=0;row<4;row++)for(int col=0;col<13;col++)Box("Key",new Vector3(-.232f+col*.033f,.046f,.15f+row*.033f),new Vector3(.025f,.008f,.023f),white,false);Box("Mouse",new Vector3(.3f,.025f,.2f),new Vector3(.065f,.04f,.105f),steel,false);
   Box("PC tower",new Vector3(.57f,.23f,-.04f),new Vector3(.22f,.46f,.4f),steel,false);Box("Power LED",new Vector3(.57f,.38f,.163f),new Vector3(.012f,.012f,.006f),screen,false);for(int j=0;j<8;j++)Box("Vent",new Vector3(.57f,.07f+j*.022f,.163f),new Vector3(.15f,.007f,.005f),wall,false);Node("Operator",new Vector3(0,0,1));PrefabUtility.SaveAsPrefabAsset(o,R+"Prefabs/Shop/Desktop computer.prefab");Object.DestroyImmediate(o);
  }
  static void BuildChair(){var o=new GameObject("Office swivel chair");root=o.transform;Box("Đệm ngồi",new Vector3(0,.49f,0),new Vector3(.49f,.12f,.47f),steel);Box("Tựa lưng",new Vector3(0,.81f,-.22f),new Vector3(.46f,.55f,.09f),steel);Box("Trụ nâng",new Vector3(0,.23f,0),new Vector3(.055f,.4f,.055f),white);foreach(float x in new[]{-.29f,.29f}){Box("Tay vịn",new Vector3(x,.69f,0),new Vector3(.065f,.06f,.39f),steel);Box("Giá tay vịn",new Vector3(x,.59f,0),new Vector3(.04f,.2f,.04f),white);}for(int i=0;i<5;i++){var spoke=Node("Chân sao",Vector3.zero);spoke.localRotation=Quaternion.Euler(0,i*72,0);Box("Nan",new Vector3(0,.08f,.16f),new Vector3(.045f,.05f,.32f),white,false,spoke);var wheel=GameObject.CreatePrimitive(PrimitiveType.Cylinder);wheel.transform.SetParent(spoke,false);wheel.transform.localPosition=new Vector3(0,.055f,.3f);wheel.transform.localRotation=Quaternion.Euler(0,0,90);wheel.transform.localScale=new Vector3(.08f,.03f,.08f);wheel.GetComponent<Renderer>().sharedMaterial=steel;Object.DestroyImmediate(wheel.GetComponent<Collider>());}PrefabUtility.SaveAsPrefabAsset(o,R+"Prefabs/Shop/Office swivel chair.prefab");Object.DestroyImmediate(o);}
  static void Computer(Vector3 p,float yaw=0){var o=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(R+"Prefabs/Shop/Desktop computer.prefab"));o.transform.SetParent(root);o.transform.SetPositionAndRotation(p,Quaternion.Euler(0,yaw,0));}
  static void Desk(float x,float z,float yaw=0){var d=Node("Bàn làm việc",new Vector3(x,0,z));Box("Mặt bàn",new Vector3(0,.83f,0),new Vector3(2.4f,.1f,1.1f),wood,true,d);foreach(float side in new[]{-.98f,.98f})Box("Chân bàn",new Vector3(side,.4f,0),new Vector3(.12f,.8f,.85f),steel,true,d);Computer(new Vector3(x,.885f,z),yaw);Prop(R+"Prefabs/Shop/Office swivel chair.prefab",new Vector3(x,0,z+1.1f),1.1f,180);Scan("office_notepads",new Vector3(x-.8f,.89f,z+.15f),.35f);Marker("cover_desk_"+x+"_"+z,new Vector3(x,0,z+1.5f));}
  static void Rack(float x,float z,bool weapons){Box(weapons?"Giá súng":"Kệ tài liệu",new Vector3(x,1.05f,z+.4f),new Vector3(.08f,2.1f,.08f),steel);Box("Trụ kệ trái",new Vector3(x-1.85f,1.05f,z),new Vector3(.08f,2.1f,.85f),steel);Box("Trụ kệ phải",new Vector3(x+1.85f,1.05f,z),new Vector3(.08f,2.1f,.85f),steel);for(int shelf=0;shelf<3;shelf++){float y=.25f+shelf*.65f;Box("Mâm kệ",new Vector3(x,y,z),new Vector3(3.8f,.08f,.85f),steel);if(weapons){for(int j=0;j<3;j++)Prop(R+"Resources/Actors/"+(j==2?"Sniper":"AK")+".prefab",new Vector3(x-1.25f+j*1.25f,y+.06f,z),1.05f,90);}else for(int j=0;j<7;j++)Scan("binder_notebook",new Vector3(x-1.5f+j*.48f,y+.06f,z),.42f,90);}}
  static void Gate(string n,Vector3 p,Vector3 size){var o=Box(n,p,size,steel);o.AddComponent<NavMeshModifier>().ignoreFromBuild=true;var obstacle=o.AddComponent<UnityEngine.AI.NavMeshObstacle>();obstacle.carving=true;obstacle.shape=UnityEngine.AI.NavMeshObstacleShape.Box;obstacle.size=Vector3.one;}
  static void BuildMap(){EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);root=new GameObject("UndergroundArmory").transform;
   Box("Sàn B1",new Vector3(0,-.25f,32),new Vector3(52,.5f,64),floor);foreach(float x in new[]{-26f,26f})Box("Tường ngoài",new Vector3(x,2.7f,32),new Vector3(.4f,5.4f,64),wall);foreach(float z in new[]{0f,64f}){Box("Tường cuối trái",new Vector3(-14,2.7f,z),new Vector3(24,5.4f,.4f),wall);Box("Tường cuối phải",new Vector3(14,2.7f,z),new Vector3(24,5.4f,.4f),wall);Box("Dầm cửa",new Vector3(0,4.6f,z),new Vector3(4,1.6f,.4f),wall);}Box("Trần",new Vector3(0,5.5f,32),new Vector3(52,.2f,64),steel);
   for(int side=-1;side<=1;side+=2)for(int row=0;row<3;row++){float x=side*16,z=12+row*19;string name=side<0?new[]{"KHO VŨ KHÍ","KHO HỒ SƠ","PHÒNG MÁY"}[row]:new[]{"VĂN PHÒNG VẬN HÀNH","PHÒNG HỌP","VĂN PHÒNG KỸ THUẬT"}[row];Node("Phòng kính / "+name,new Vector3(x,0,z));foreach(float end in new[]{z-8.5f,z+8.5f})Box("Vách phòng / "+name,new Vector3(x,2,end),new Vector3(18,.0f+4,.16f),glass);
    float edge=side*7;foreach(float dz in new[]{-5f,5f})Box("Kính an toàn / "+name,new Vector3(edge,2,z+dz),new Vector3(.14f,4,7),glass);Box("Khung cửa / "+name,new Vector3(edge,3.65f,z),new Vector3(.2f,.3f,3),steel);foreach(float dz in new[]{-1.5f,1.5f})Box("Trụ cửa",new Vector3(edge,1.9f,z+dz),new Vector3(.22f,3.8f,.22f),steel);Sign(name,new Vector3(edge-side*.2f,3.3f,z),side<0?-90:90);Marker("room_"+side+"_"+row,new Vector3(side*9,0,z));
    foreach(var plant in new[]{new Vector3(side*8.8f,0,z-7.5f),new Vector3(side*8.8f,0,z+7.5f),new Vector3(side*24.6f,0,z-7.5f)})Scan("potted_plant_02",plant,1.4f);Box("Tủ y tế gắn tường",new Vector3(side*25.65f,1.5f,z+6),new Vector3(.35f,.9f,.8f),white);Scan("medical_box",new Vector3(side*25.35f,1.2f,z+6),.6f,side<0?90:-90);Box("Dấu thập y tế đứng",new Vector3(side*25.44f,1.9f,z+6),new Vector3(.025f,.25f,.065f),red,false);Box("Dấu thập y tế ngang",new Vector3(side*25.44f,1.9f,z+6),new Vector3(.025f,.065f,.25f),red,false);Point("supply_room_"+side+"_"+row,"TỦ Y TẾ / TIẾP TẾ",new Vector3(side*24.6f,1.1f,z+6));
    if(side<0&&row==0){for(int j=0;j<4;j++)foreach(float rx in new[]{-22f,-16.8f,-11.6f})Rack(rx,5+j*2.8f,true);Box("Bàn chọn vũ khí",new Vector3(-12,.65f,16),new Vector3(5,1.3f,1.2f),wood);Prop(R+"Resources/Actors/AK.prefab",new Vector3(-14,1.32f,16),1,90);Prop(R+"Resources/Actors/Sniper.prefab",new Vector3(-12,1.32f,16),1.15f,90);Point("ak","LẤY AK47",new Vector3(-14,1,17));Point("sniper","LẤY M700 / SÚNG NGẮM",new Vector3(-12,1,17));Point("grenades","LẤY KÍNH NHÌN ĐÊM / LỰU ĐẠN / ĐẠN",new Vector3(-10,1,17));Prop(R+"Resources/Actors/NightVisionGoggles.prefab",new Vector3(-9.5f,1.5f,16),.35f,180).name="Kính nhìn đêm tại kho";for(int k=0;k<6;k++)Box("Hộp lựu đạn",new Vector3(-10+(k%2)*.3f,1.42f,15.7f+k/2*.25f),new Vector3(.2f,.2f,.18f),steel,false);}
    else if(side<0&&row==1){for(int j=0;j<6;j++)foreach(float rx in new[]{-22f,-16.8f,-11.6f})Rack(rx,z-7+j*2.8f,false);}
    else if(side<0){for(int j=0;j<4;j++)foreach(float mx in new[]{-23f,-17.5f,-12f}){Scan("portable_generator",new Vector3(mx,0,z-6+j*4),1.7f,90);Box("Tủ máy chủ",new Vector3(mx+2.3f,1.2f,z-6+j*4),new Vector3(1.2f,2.4f,1),steel);for(int k=0;k<7;k++)Box("Máy chủ / đèn trạng thái",new Vector3(mx+2.92f,.4f+k*.25f,z-6+j*4),new Vector3(.025f,.055f,.65f),screen,false);}}
    else if(row==1){foreach(float tx in new[]{11f,16.5f,22f}){Box("Bàn họp lớn",new Vector3(tx,.83f,z),new Vector3(3,.16f,10),wood);foreach(float sx in new[]{tx-2.1f,tx+2.1f})for(int j=0;j<5;j++)Prop(R+"Prefabs/Shop/Office swivel chair.prefab",new Vector3(sx,0,z-4+j*2),1.1f,sx<tx?90:-90);for(int j=0;j<5;j++)Scan("office_notepads",new Vector3(tx-1,.94f,z-4+j*2),.4f);Computer(new Vector3(tx,.93f,z-3));}}
    else{for(int j=0;j<6;j++)foreach(float dx in new[]{11.5f,17f,22.5f})Desk(dx,z-7+j*2.6f);if(row==0){Point("base_computer","MÁY TÍNH VẬN HÀNH / CẮM USB",new Vector3(11.5f,1,z+7.1f));Sign("MÁY TÍNH VẬN HÀNH",new Vector3(11.5f,2.4f,z+6));}}
   }
   foreach(float x in new[]{-5f,5f})for(float z=8;z<62;z+=7){Box("Cột chịu lực",new Vector3(x,2.7f,z),new Vector3(1.2f,5.4f,1.2f),wall);Box("Đai an toàn",new Vector3(x,.8f,z),new Vector3(1.23f,.15f,1.23f),white);Marker("cover_pillar_"+x+"_"+z,new Vector3(x,0,z+1.1f));}
   for(float z=6;z<64;z+=8)foreach(float x in new[]{-17f,0,17f}){Box("Đèn trần",new Vector3(x,5.1f,z),new Vector3(3,.08f,.3f),screen,false);var l=Node("Đèn B1",new Vector3(x,4.8f,z)).gameObject.AddComponent<Light>();l.type=LightType.Point;l.range=13;l.intensity=18;l.color=new Color(.75f,.86f,1);}
   // Continuous, navmesh-baked staircase from Door 006 to the hall.
   for(int i=0;i<20;i++){float z=-10+i*.5f,y=3-i*.15f;Box("Bậc thang 006",new Vector3(0,y-.15f,z),new Vector3(4,.3f,.51f),wall);}var darkness=Mat("006 darkness",Color.black);darkness.shader=Shader.Find("Universal Render Pipeline/Unlit");darkness.color=Color.black;Box("Khoảng tối sau 006",new Vector3(0,4.6f,-20.5f),new Vector3(4.5f,5,.2f),darkness,false);Box("Chiếu nghỉ 006",new Vector3(0,2.8f,-15),new Vector3(4,.4f,10),floor);foreach(float side in new[]{-2.2f,2.2f})Box("Hành lang tối 006",new Vector3(side,4.5f,-16.75f),new Vector3(.3f,5,7.5f),darkness);Box("Trần khoảng tối",new Vector3(0,6.6f,-16),new Vector3(4.5f,.2f,9),darkness);foreach(float x in new[]{-2.2f,2.2f})Box("Tường cầu thang 006",new Vector3(x,3,-6),new Vector3(.3f,8,14),wall);Box("Trần 006",new Vector3(0,6.5f,-6),new Vector3(4.5f,.2f,14),steel);Gate("Breach intact",new Vector3(0,4.6f,-11),new Vector3(4,3.2f,.25f));var wreck=Box("Breach wreck",new Vector3(1.5f,3.15f,-10),new Vector3(.9f,.15f,1.8f),steel,false);wreck.SetActive(false);Sign("006",new Vector3(0,6,-10.8f));var stairLight=Node("Đèn cửa 006",new Vector3(0,5.8f,-9)).gameObject.AddComponent<Light>();stairLight.range=13;stairLight.intensity=20;Marker("breach",new Vector3(0,3,-11));for(int i=0;i<4;i++)Marker("enemy_"+i,new Vector3(-.9f+(i%2)*1.8f,3.1f,-17+(i/2)*.8f));Marker("spawn",new Vector3(0,.1f,4));Marker("combat_spawn",new Vector3(-17,.1f,18));Marker("combat_focus",new Vector3(0,0,28));
   Gate("Retreat gate",new Vector3(0,1.8f,63),new Vector3(4,3.6f,.3f));Point("retreat","XUỐNG TRUNG TÂM ĐIỀU PHỐI",new Vector3(0,1,60));root.GetComponentsInChildren<Interaction>().First(i=>i.id=="retreat").title="XUỐNG TRUNG TÂM ĐIỀU PHỐI";for(int i=0;i<16;i++)Box("Bậc thang xuống B2",new Vector3(0,-i*.15f-.15f,64+i*.4f),new Vector3(4,.3f,.41f),wall);Marker("retreat_end",new Vector3(0,-2.2f,69));
   var ramp=Box("Mặt dốc điều hướng 006",new Vector3(0,1.4f,-5),new Vector3(3.95f,.12f,10.55f),wall);ramp.transform.rotation=Quaternion.Euler(16.7f,0,0);ramp.GetComponent<Renderer>().enabled=false;
   var nav=root.gameObject.AddComponent<NavMeshSurface>();nav.collectObjects=CollectObjects.Children;nav.useGeometry=UnityEngine.AI.NavMeshCollectGeometry.PhysicsColliders;nav.overrideVoxelSize=true;nav.voxelSize=.08f;nav.BuildNavMesh();string np=A+"ArmoryNav.asset";var old=AssetDatabase.LoadAssetAtPath<UnityEngine.AI.NavMeshData>(np);if(old){EditorUtility.CopySerialized(nav.navMeshData,old);nav.RemoveData();nav.navMeshData=old;nav.AddData();}else AssetDatabase.CreateAsset(nav.navMeshData,np);PrefabUtility.SaveAsPrefabAsset(root.gameObject,R+"Resources/Worlds/UndergroundArmory.prefab");EditorSceneManager.SaveScene(EditorSceneManager.GetActiveScene(),R+"Scenes/UndergroundArmory_Environment.unity");
  }
  static void PatchShop(){string path=R+"Resources/Worlds/NorthPointShop.prefab";var shop=PrefabUtility.LoadPrefabContents(path);root=shop.transform;try{var laptops=shop.GetComponentsInChildren<Transform>(true).Where(t=>t.name.StartsWith("Laptop -")||t.name=="classic_laptop").ToArray();foreach(var laptop in laptops){if(!laptop||laptop.GetComponentsInChildren<Renderer>().Length==0)continue;var b=BoundsOf(laptop.gameObject);var pos=new Vector3(b.center.x,b.min.y,b.center.z);Computer(pos,0);Object.DestroyImmediate(laptop.gameObject);}var terminal=shop.GetComponentsInChildren<Interaction>(true).FirstOrDefault(i=>i.id=="computer");if(terminal)terminal.transform.position=new Vector3(-9.75f,1.02f,28.1f);foreach(var t in shop.GetComponentsInChildren<Transform>(true).Where(t=>t.name=="Lối tối xuống B1").ToArray())Object.DestroyImmediate(t.gameObject);PrefabUtility.SaveAsPrefabAsset(shop,path);}finally{PrefabUtility.UnloadPrefabContents(shop);}}
 }
}
