using System.IO;
using System.Linq;
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using Unity.AI.Navigation;
namespace BlackMarket.Editor {
 public static class UndergroundBuilder {
  const string Root="Assets/BlackMarket/";static GameObject world;static Material concrete,metal,floor,orange,screen,white;static int props;
  [MenuItem("BLACK MARKET/Build underground campaign")]
  public static void BuildControlOnly(){controlOnly=true;Build();controlOnly=false;}
  static bool controlOnly;
  public static void Build(){
   Directory.CreateDirectory(Root+"Art/Underground/Materials");AssetDatabase.Refresh();
   concrete=Mat("Concrete",new Color(.22f,.25f,.25f));metal=Mat("Steel",new Color(.09f,.13f,.14f));floor=Mat("Floor",new Color(.45f,.48f,.48f));var sourceFloor=AssetDatabase.LoadAssetAtPath<Material>(Root+"Resources/Materials/concrete_floor_02.mat");if(sourceFloor){floor.CopyPropertiesFromMaterial(sourceFloor);floor.mainTextureScale=new Vector2(12,16);}orange=Mat("Warning",new Color(.85f,.43f,.08f));screen=Mat("Screen",new Color(.02f,.25f,.32f),true);white=Mat("Light",new Color(.65f,.8f,.85f),true);
   foreach(var name in new[]{"ammo_box","industrial_storage_cart","industrial_caged_sconce"})ImportMaterial(name);
   if(!controlOnly)BuildWorld(false);BuildWorld(true);PatchArmoryGear();if(!controlOnly)PatchUsb();AssetDatabase.SaveAssets();EditorSceneManager.OpenScene(Root+"Scenes/NorthPoint.unity");Debug.Log("UNDERGROUND BUILD COMPLETE / "+props+" props");
  }
  static Material Mat(string name,Color color,bool emission=false){string path=Root+"Art/Underground/Materials/"+name+".mat";var m=AssetDatabase.LoadAssetAtPath<Material>(path);if(!m){m=new Material(Shader.Find("Universal Render Pipeline/Lit"));AssetDatabase.CreateAsset(m,path);}m.color=color;m.SetFloat("_Smoothness",.28f);if(emission){m.EnableKeyword("_EMISSION");m.SetColor("_EmissionColor",color*2);}return m;}
  static void ImportMaterial(string name){string dir=Root+"Art/Underground/Sources/"+name;var m=Mat(name,Color.white);foreach(var path in Directory.GetFiles(dir,"*.png")){var ti=AssetImporter.GetAtPath(path) as TextureImporter;if(ti){ti.maxTextureSize=1024;if(path.Contains("nor_gl"))ti.textureType=TextureImporterType.NormalMap;ti.SaveAndReimport();}var t=AssetDatabase.LoadAssetAtPath<Texture2D>(path);if(path.ToLower().Contains("diff"))m.SetTexture("_BaseMap",t);if(path.Contains("metallic_smoothness")){if(ti){ti.sRGBTexture=false;ti.SaveAndReimport();}m.SetTexture("_MetallicGlossMap",t);m.SetFloat("_Smoothness",1);m.EnableKeyword("_METALLICSPECGLOSSMAP");}if(path.Contains("nor_gl")){m.SetTexture("_BumpMap",t);m.EnableKeyword("_NORMALMAP");}}}
  static GameObject Box(string name,Vector3 p,Vector3 scale,Material mat,bool collider=true){var o=GameObject.CreatePrimitive(PrimitiveType.Cube);o.name=name;o.transform.SetParent(world.transform);o.transform.position=p;o.transform.localScale=scale;o.GetComponent<Renderer>().sharedMaterial=mat;if(!collider)Object.DestroyImmediate(o.GetComponent<Collider>());return o;}
  static void Marker(string id,Vector3 p){var o=new GameObject(id);o.transform.SetParent(world.transform);o.transform.position=p;o.AddComponent<WorldMarker>().id=id;}
  static void Sign(string text,Vector3 p,float width=1){var o=new GameObject(text);o.transform.SetParent(world.transform);o.transform.position=p;o.transform.rotation=Quaternion.identity;var t=o.AddComponent<TextMesh>();t.text=text;t.font=Resources.Load<Font>("Fonts/Bold");t.fontSize=64;t.characterSize=.055f*width;t.anchor=TextAnchor.MiddleCenter;t.color=new Color(.7f,.88f,.88f);o.GetComponent<Renderer>().sharedMaterial=t.font.material;o.AddComponent<WorldTextDepth>();if(text.StartsWith("006"))o.transform.rotation=Quaternion.Euler(0,180,0);if(text.StartsWith("NGUỒN"))o.transform.rotation=Quaternion.Euler(0,-90,0);}
  static void Point(string id,string title,Vector3 p){var o=new GameObject(title);o.transform.SetParent(world.transform);o.transform.position=p;var i=o.AddComponent<Interaction>();i.id=id;i.title=title;}
  static GameObject Prop(string path,Vector3 p,float width,float angle=0,Material overrideMat=null){var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(path);if(!prefab){Debug.LogError("Missing prop "+path);return null;}var o=Object.Instantiate(prefab,world.transform);o.transform.position=Vector3.zero;if(!path.Contains("Underground/Sources/"))o.transform.rotation=Quaternion.identity;foreach(var i in o.GetComponentsInChildren<Interaction>())Object.DestroyImmediate(i);foreach(var c in o.GetComponentsInChildren<Collider>())Object.DestroyImmediate(c);var rs=o.GetComponentsInChildren<Renderer>();if(rs.Length==0)return o;var bounds=rs[0].bounds;foreach(var r in rs)bounds.Encapsulate(r.bounds);float scale=width/Mathf.Max((path.Contains("Resources/Actors/")||path.Contains("Underground/Sources/"))?Mathf.Max(bounds.size.x,bounds.size.y,bounds.size.z):bounds.size.x,.001f);o.transform.localScale*=scale;var center=bounds.center*scale;var bottom=bounds.min.y*scale;foreach(var r in rs)if(overrideMat)r.sharedMaterials=r.sharedMaterials.Select(x=>overrideMat).ToArray();o.transform.position=new Vector3(-center.x,-bottom,-center.z);var holder=new GameObject(prefab.name);holder.transform.SetParent(world.transform);o.transform.SetParent(holder.transform,true);holder.transform.SetPositionAndRotation(p,Quaternion.Euler(0,angle,0));props++;return holder;}
  static GameObject Shop(string name,Vector3 p,float width,float angle=0)=>Prop(Root+"Prefabs/Shop/"+name+".prefab",p,width,angle);
  static void Scan(string name,Vector3 p,float width,float angle=0)=>Prop(Root+"Art/Underground/Sources/"+name+"/"+name+"_1k.fbx",p,width,angle,AssetDatabase.LoadAssetAtPath<Material>(Root+"Art/Underground/Materials/"+name+".mat"));
  static void Gate(string name,Vector3 p,Vector3 size){var o=Box(name,p,size,metal);o.AddComponent<NavMeshModifier>().ignoreFromBuild=true;var obstacle=o.AddComponent<UnityEngine.AI.NavMeshObstacle>();obstacle.shape=UnityEngine.AI.NavMeshObstacleShape.Box;obstacle.size=Vector3.one;obstacle.carving=true;}
  static void Desk(float x,float z,bool central=false){var block=Box("Bàn / vật che",new Vector3(x,.55f,z),new Vector3(3.2f,1.1f,1.2f),metal);Shop("Desktop computer",new Vector3(x,1.12f,z),1.1f,180);Shop("Chair - ghe nhua",new Vector3(x,0,z+1.35f),.65f,180);Marker("cover_"+x+"_"+z,new Vector3(x,0,z+1.7f));}
  static void BuildWorld(bool control){
   EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);world=new GameObject(control?"UndergroundControl":"UndergroundArmory");float depth=control?52:64;
   Box("Sàn bê tông",new Vector3(0,-.25f,depth/2),new Vector3(44,.5f,depth),floor);Box("Tường trái",new Vector3(-22,2.8f,depth/2),new Vector3(.5f,5.6f,depth),concrete);Box("Tường phải",new Vector3(22,2.8f,depth/2),new Vector3(.5f,5.6f,depth),concrete);Box("Tường lối vào trái",new Vector3(-12.5f,2.8f,0),new Vector3(19,5.6f,.5f),concrete);Box("Tường lối vào phải",new Vector3(12.5f,2.8f,0),new Vector3(19,5.6f,.5f),concrete);Box("Dầm cửa vào",new Vector3(0,4.6f,0),new Vector3(6,2,.5f),concrete);Box("Hành lang từ cầu thang",new Vector3(0,-.2f,-4),new Vector3(6,.4f,8),floor);foreach(float x in new[]{-3f,3f})Box("Vách cầu thang",new Vector3(x,2,-4),new Vector3(.4f,4,8),concrete);Box("Trần cầu thang",new Vector3(0,4,-4),new Vector3(6,.3f,8),metal);Box("Cuối cầu thang tối",new Vector3(0,2,-8),new Vector3(6,4,.3f),metal);Sign("006 / CẦU THANG AN NINH",new Vector3(0,3.8f,1.25f),.65f);
   if(control){for(int step=0;step<16;step++)Box("Bậc thang B3",new Vector3(0,3-step*.2f-.15f,-8+step*.5f),new Vector3(5.5f,.3f,.51f),concrete);foreach(Transform t in world.transform){if(t.name=="Trần cầu thang")t.position=new Vector3(0,6.5f,-4);if(t.name=="Vách cầu thang"){t.position=new Vector3(t.position.x,3,-4);t.localScale=new Vector3(.4f,6,8);}if(t.name=="Cuối cầu thang tối"){t.position=new Vector3(0,3,-8.3f);t.localScale=new Vector3(6,6,.3f);var dark=Mat("Stair darkness",Color.black);dark.shader=Shader.Find("Universal Render Pipeline/Unlit");t.GetComponent<Renderer>().sharedMaterial=dark;}}}
   if(control)Box("Tường sau",new Vector3(0,2.8f,depth),new Vector3(44,5.6f,.5f),concrete);else{Box("Tường sau trái",new Vector3(-12,2.8f,depth),new Vector3(20,5.6f,.5f),concrete);Box("Tường sau phải",new Vector3(12,2.8f,depth),new Vector3(20,5.6f,.5f),concrete);}
   Box("Trần",new Vector3(0,5.7f,depth/2),new Vector3(44,.25f,depth),metal);
   for(float z=6;z<depth;z+=8){Box("Dầm ngang",new Vector3(0,5.25f,z),new Vector3(44,.35f,.3f),metal);foreach(float x in new[]{-14f,0,14f}){Box("Đèn trần",new Vector3(x,5.05f,z),new Vector3(3,.1f,.3f),white,false);var o=new GameObject("Đèn chiếu sáng");o.transform.SetParent(world.transform);o.transform.position=new Vector3(x,4.7f,z);var l=o.AddComponent<Light>();l.type=LightType.Point;l.range=12;l.intensity=15;l.color=new Color(.65f,.82f,.9f);l.shadows=LightShadows.None;}}
   foreach(float x in new[]{-14f,14f})for(float z=18;z<depth-7;z+=10){Box("Cột chịu lực",new Vector3(x,2.7f,z),new Vector3(1.2f,5.4f,1.2f),concrete);Box("Sọc cảnh báo",new Vector3(x,.75f,z),new Vector3(1.23f,.3f,1.23f),orange);Marker("cover_pillar"+x+"_"+z,new Vector3(x,0,z+1));}
   if(!control)for(float z=20;z<depth-10;z+=10)foreach(float x in new[]{-7f,7f})Desk(x,z);
   else for(int row=0;row<3;row++)for(int col=0;col<7;col++){
    float a=(-34+col*68f/6)*Mathf.Deg2Rad,r=14+row*10;var p=new Vector3(Mathf.Sin(a)*r,0,50-Mathf.Cos(a)*r);float yaw=-a*Mathf.Rad2Deg;
    var desk=Box("Bàn điều phối vòng cung",p+Vector3.up*.55f,new Vector3(2.7f,1.1f,1.2f),metal);desk.transform.rotation=Quaternion.Euler(0,yaw,0);
    Shop("Desktop computer",p+Vector3.up*1.12f,1.05f,yaw+180);Shop("Office swivel chair",p-Quaternion.Euler(0,yaw,0)*Vector3.forward*1.1f,.65f,yaw);
    Marker("cover_arc_"+row+"_"+col,p-Quaternion.Euler(0,yaw,0)*Vector3.forward*1.6f);
   }
   if(control)foreach(float x in new[]{-19f,19f})foreach(float z in new[]{7f,12f,39f,44f,48f}){Shop("Stockroom steel rack - ke kho",new Vector3(x,0,z),3,90);Box("Kệ thùng hồ sơ",new Vector3(x,.85f,z),new Vector3(1.2f,1.7f,3),metal);for(int n=0;n<6;n++)Box("Thùng tài liệu niêm phong",new Vector3(x,1.9f+(n/3)*.45f,z-.9f+(n%3)*.9f),new Vector3(.8f,.4f,.7f),concrete,false);Marker("cover_archive_"+x+"_"+z,new Vector3(x>0?x-1.4f:x+1.4f,0,z));}
   for(float z=17;z<depth-7;z+=8)foreach(float x in new[]{-19f,19f}){Shop("Stockroom steel rack - ke kho",new Vector3(x,0,z),3.2f,90);var rackBlock=Box("Kệ / vật che",new Vector3(x,.85f,z),new Vector3(1.1f,1.7f,3.2f),metal);rackBlock.GetComponent<Renderer>().enabled=false;if(!control)Prop(Root+"Resources/Actors/AK.prefab",new Vector3(x,1.8f,z),.95f,90);else for(int k=0;k<6;k++)Box("Classeurs / dossiers",new Vector3(x,1.8f,z-1+k*.35f),new Vector3(.65f,.35f,.24f),k%2==0?concrete:orange,false);for(int j=0;j<3;j++)Scan("ammo_box",new Vector3(x,.95f,z-1+j),.65f,90);if(control){Box("Tủ máy chủ",new Vector3(x,1.3f,z+3),new Vector3(1.1f,2.6f,1),metal);for(int y=0;y<6;y++)Box("Trạng thái máy chủ",new Vector3(x-.56f,.5f+y*.32f,z+3),new Vector3(.02f,.05f,.6f),screen,false);}}
   for(int i=0;i<4;i++)Scan("industrial_storage_cart",new Vector3(i%2==0?-17:17,0,24+i*6),1.2f,90);
   for(float z=12;z<depth;z+=16){Scan("industrial_caged_sconce",new Vector3(-21.6f,2.6f,z),.4f,90);var o=new GameObject("Emergency / đèn dự phòng");o.transform.SetParent(world.transform);o.transform.position=new Vector3(0,4,z);var l=o.AddComponent<Light>();l.range=13;l.intensity=.12f;l.color=new Color(.2f,.5f,.35f);}
   for(int i=0;i<12;i++){Box("Repère au sol",new Vector3(-2,.015f,8+i*3.7f),new Vector3(.08f,.015f,1.6f),orange,false);Box("Repère au sol",new Vector3(2,.015f,8+i*3.7f),new Vector3(.08f,.015f,1.6f),orange,false);}
   Marker("spawn",new Vector3(0,.1f,6));Marker("breach",new Vector3(0,0,control?-5:2));Marker("combat_focus",new Vector3(0,0,30));for(int i=0;i<4;i++)Marker("enemy_"+i,new Vector3(control?(-1.5f+i):(-4+i*2.7f),control?2:.1f,control?-5:4));
   Gate("Breach intact",new Vector3(0,1.8f,control?-6:1),new Vector3(5,3.6f,.3f));var wreck=Box("Breach wreck",new Vector3(3,.25f,control?-5:2),new Vector3(2,.35f,1.2f),metal,false);wreck.transform.rotation=Quaternion.Euler(0,25,12);wreck.SetActive(false);
   if(!control){
    Sign("B1 / QUÂN GIỚI — KHU VỰC HẠN CHẾ",new Vector3(0,4,63));
    foreach(float x in new[]{-12f,-6,0}){Box("Bàn quân giới",new Vector3(x,.65f,12),new Vector3(4,1.3f,1.5f),metal);}
    Prop(Root+"Resources/Actors/Pistol.prefab",new Vector3(-12,1.32f,12),.65f);Point("pistol","LẤY SÚNG LỤC",new Vector3(-12,1.2f,11));Prop(Root+"Resources/Actors/AK.prefab",new Vector3(-6,1.32f,12),1.1f);Point("ak","LẤY AK",new Vector3(-6,1.2f,11));Scan("ammo_box",new Vector3(0,1.32f,12),.85f);Point("grenades","LẤY LỰU ĐẠN / ĐẠN",new Vector3(0,1.2f,11));
    Desk(17,21);Point("base_computer","MÁY TÍNH VẬN HÀNH / USB",new Vector3(17,1,22.1f));Sign("MÁY TÍNH VẬN HÀNH",new Vector3(17,2.6f,22));
    Point("retreat","XUỐNG TRUNG TÂM ĐIỀU PHỐI",new Vector3(0,1,60));Gate("Retreat gate",new Vector3(0,1.8f,63),new Vector3(4,3.6f,.3f));Box("Hành lang rút lui",new Vector3(0,-.3f,67),new Vector3(4,.6f,8),floor);for(int i=0;i<12;i++)Box("Bậc thang",new Vector3(0,-i*.2f-.2f,65+i*.4f),new Vector3(4,.4f,.42f),concrete);Marker("retreat_end",new Vector3(0,-2.2f,69));Box("Bóng tối cầu thang",new Vector3(0,-.5f,70),new Vector3(4,4,.1f),metal,false);
   }else{
    var breaker=Box("Tủ điện chiếu sáng",new Vector3(-9,1.8f,51.45f),new Vector3(1.1f,1.5f,.55f),orange);breaker.AddComponent<LightingBreaker>();Point("breaker","TỦ ĐIỆN / BẮN ĐỂ PHÁ",new Vector3(-9,1.5f,50));Sign("NGUỒN CHIẾU SÁNG",new Vector3(-9,2.8f,51.1f),.65f);
    var display=Mat("ControlDisplay",Color.white);display.SetTexture("_BaseMap",AssetDatabase.LoadAssetAtPath<Texture2D>(Root+"Art/Underground/control_display.png"));display.EnableKeyword("_EMISSION");display.SetTexture("_EmissionMap",display.mainTexture);display.SetColor("_EmissionColor",Color.white*.65f);display.SetTextureScale("_BaseMap",new Vector2(-1,-1));display.SetTextureOffset("_BaseMap",Vector2.one);Box("Màn hình điều phối trung tâm",new Vector3(0,3.3f,51.5f),new Vector3(18,4,.2f),display,false);Sign("NORTH POINT / ĐIỀU PHỐI\nMÁY CHỦ LƯU TRỮ ORDER 71",new Vector3(0,5.25f,51.3f),.7f);for(int i=0;i<7;i++)Box("Dữ liệu hiển thị",new Vector3(-7+i*2.3f,2.1f,51.3f),new Vector3(1.5f,.08f,.02f),white,false);
    Desk(0,47,true);Point("control_entry","KHẢO SÁT MÀN HÌNH TRUNG TÂM",new Vector3(0,1,44));Point("final_terminal","MÁY CHỦ TRUNG TÂM / CẮM USB",new Vector3(0,1,45.5f));Point("escape","CẦU THANG / TRỞ LÊN CỬA HÀNG",new Vector3(0,1,1.5f));Sign("LỐI THOÁT: QUAY LẠI CẦU THANG 006",new Vector3(0,3.5f,1.25f),.65f);
   }
   for(int i=0;i<3;i++){Scan("ammo_box",new Vector3(i%2==0?-11:11,0,28+i*9),.8f);Point("supply_"+i,"HỘP TIẾP TẾ",new Vector3(i%2==0?-11:11,.4f,28+i*9));}
   var nav=world.AddComponent<NavMeshSurface>();nav.collectObjects=CollectObjects.Children;nav.useGeometry=UnityEngine.AI.NavMeshCollectGeometry.PhysicsColliders;nav.BuildNavMesh();string navPath=Root+"Art/Underground/"+world.name+"Nav.asset";var old=AssetDatabase.LoadAssetAtPath<UnityEngine.AI.NavMeshData>(navPath);if(old){EditorUtility.CopySerialized(nav.navMeshData,old);nav.RemoveData();nav.navMeshData=old;nav.AddData();}else AssetDatabase.CreateAsset(nav.navMeshData,navPath);
   string prefabPath=Root+"Resources/Worlds/"+world.name+".prefab";PrefabUtility.SaveAsPrefabAsset(world,prefabPath);Object.DestroyImmediate(world);var instance=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath));EditorSceneManager.SaveScene(EditorSceneManager.GetActiveScene(),Root+"Scenes/"+instance.name+"_Environment.unity");
  }
  static void PatchArmoryGear(){var path=Root+"Resources/Worlds/UndergroundArmory.prefab";var o=PrefabUtility.LoadPrefabContents(path);var item=o.GetComponentsInChildren<Interaction>(true).First(i=>i.id=="grenades");item.title="LẤY KÍNH NHÌN ĐÊM / LỰU ĐẠN / ĐẠN";if(!o.transform.Find("Kính nhìn đêm tại kho")){var goggles=Object.Instantiate(Resources.Load<GameObject>("Actors/NightVisionGoggles"),o.transform);goggles.name="Kính nhìn đêm tại kho";goggles.transform.localPosition=new Vector3(-9.5f,1.5f,16);goggles.transform.localRotation=Quaternion.Euler(0,180,0);}PrefabUtility.SaveAsPrefabAsset(o,path);PrefabUtility.UnloadPrefabContents(o);}
  static void PatchUsb(){string path=Root+"Resources/Worlds/NorthPointShop.prefab";var root=PrefabUtility.LoadPrefabContents(path);try{var item=root.GetComponentsInChildren<Interaction>(true).FirstOrDefault(i=>i.id=="keycard");if(item){item.title="USB ĐỎ / KHÓA BẢO MẬT CỦA MARCUS";foreach(Transform child in item.transform.Cast<Transform>().ToArray())if(child.name=="USB đỏ")Object.DestroyImmediate(child.gameObject);foreach(var r in item.GetComponentsInChildren<Renderer>())r.enabled=false;var usb=GameObject.CreatePrimitive(PrimitiveType.Cube);usb.name="USB đỏ";usb.transform.SetParent(item.transform,false);usb.transform.localScale=new Vector3(.12f/item.transform.lossyScale.x,.025f/item.transform.lossyScale.y,.055f/item.transform.lossyScale.z);usb.GetComponent<Renderer>().sharedMaterial=Mat("USB Red",new Color(.65f,.025f,.02f));Object.DestroyImmediate(usb.GetComponent<Collider>());var plug=GameObject.CreatePrimitive(PrimitiveType.Cube);plug.transform.SetParent(usb.transform,false);plug.transform.localPosition=new Vector3(.62f,0,0);plug.transform.localScale=new Vector3(.3f,.7f,.8f);plug.GetComponent<Renderer>().sharedMaterial=white;Object.DestroyImmediate(plug.GetComponent<Collider>());}PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}}
 }
}
