using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.InputSystem;
namespace BlackMarket {
 [DefaultExecutionOrder(200)]
 public class ArmoryRevisionSelfTest:MonoBehaviour {
  float lastLeftGripError=100;string capturePath;Camera captureCamera;
  Campaign g;List<string> log=new List<string>();int failures;float deadline;bool done;Camera preview;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Launch(){if(Array.IndexOf(Environment.GetCommandLineArgs(),"--armory-revision-check")>=0)new GameObject("Armory revision QA").AddComponent<ArmoryRevisionSelfTest>();}
  void Check(bool ok,string msg){string s=(ok?"PASS ":"FAIL ")+msg;log.Add(s);Debug.Log(s);if(!ok)failures++;}
  Interaction Item(string id)=>g.level.GetComponentsInChildren<Interaction>(true).First(i=>i.id==id);
  void Move(Vector3 p){g.player.body.enabled=false;g.player.transform.position=p;g.player.body.enabled=true;}
  IEnumerator Frame(){if(Application.isBatchMode)yield return null;else yield return new WaitForEndOfFrame();}
  void Capture(string path,Camera camera){if(Application.isBatchMode){captureCamera=camera;capturePath=path;}else ScreenCapture.CaptureScreenshot(path);}
  IEnumerator Picture(string name,Vector3 eye,Vector3 target){bool hide=name.StartsWith("04")||name.StartsWith("05")||name.StartsWith("06")||name.StartsWith("07")||name.StartsWith("10");bool wasAim=g.player.touchAim;if(hide){g.ui.enabled=false;g.player.touchAim=wasAim;}preview.transform.SetPositionAndRotation(eye,Quaternion.LookRotation(target-eye));preview.enabled=true;g.view.enabled=false;yield return null;yield return Frame();Capture("Documentation/ArmoryRevisionPreview/"+name+".png",preview);yield return null;yield return null;preview.enabled=false;g.view.enabled=true;g.ui.enabled=true;g.player.touchAim=wasAim;}
  IEnumerator Start(){if(Keyboard.current!=null)InputSystem.DisableDevice(Keyboard.current);if(Mouse.current!=null)InputSystem.DisableDevice(Mouse.current);deadline=Time.realtimeSinceStartup+600;Application.runInBackground=true;Directory.CreateDirectory("Documentation/ArmoryRevisionPreview");yield return null;g=Campaign.Instance;g.sound.Play("beep",.1f);Check(g.sound.GetComponentsInChildren<AudioSource>().Any(a=>a.clip&&a.clip.name=="beep"&&Mathf.Abs(a.volume-.3f)<.001f),"effects volume boosted three times");g.sound.Play("hunt_shout",1);Check(!g.sound.GetComponentsInChildren<AudioSource>().Any(a=>a.clip&&a.clip.name=="hunt_shout"&&a.isPlaying),"synthetic speech disabled");preview=new GameObject("QA camera").AddComponent<Camera>();preview.nearClipPlane=.03f;preview.fieldOfView=60;preview.enabled=false;
   g.state=new CampaignSave{stage=1,keycard=true,introCompleted=true};g.LoadWorld(1);yield return null;
   Check(g.level.GetComponentsInChildren<WorldMarker>().Count(m=>m.id.StartsWith("room_"))==6,"six rooms");Check(g.level.GetComponentsInChildren<Transform>().Count(t=>t.name=="Cột chịu lực")==16,"sixteen cover pillars");Check(!g.level.GetComponentsInChildren<Interaction>().Any(i=>i.id=="pistol"),"no pistol pickup in map 2");
   var children=g.level.transform.Cast<Transform>().ToArray();Check(children.Count(t=>t.name=="Giá súng")==12,"triple weapon racks: 12");Check(children.Count(t=>t.name=="Kệ tài liệu")==18,"triple document shelves: 18");Check(children.Count(t=>t.name=="Bàn làm việc")==36,"triple work desks: 36");Check(children.Count(t=>t.name=="Bàn họp lớn")==3,"triple meeting tables: 3");Check(children.Count(t=>t.name.StartsWith("Desktop computer"))==39,"triple computers: 39");Check(children.Count(t=>t.name.StartsWith("potted_plant"))==18,"triple plants: 18");Check(children.Count(t=>t.name.StartsWith("portable_generator"))==12,"triple generators: 12");Check(children.Count(t=>t.name=="Tủ máy chủ")==12,"triple machine cabinets: 12");Check(!g.level.transform.Find("Vách cuối chiếu nghỉ 006")&&g.level.transform.Find("Khoảng tối sau 006"),"black depth behind entry, no wall at spawn");
   foreach(var id in new[]{"ak","sniper","grenades","base_computer","retreat"}){NavMesh.SamplePosition(Item(id).transform.position,out var hit,2,NavMesh.AllAreas);var path=new NavMeshPath();Check(NavMesh.CalculatePath(g.Marker("spawn").position,hit.position,NavMesh.AllAreas,path)&&path.status==NavMeshPathStatus.PathComplete,"walkable "+id);}
   foreach(var m in g.level.GetComponentsInChildren<WorldMarker>().Where(m=>m.id.StartsWith("room_"))){var path=new NavMeshPath();Check(NavMesh.CalculatePath(g.Marker("spawn").position,m.transform.position,NavMesh.AllAreas,path)&&path.status==NavMeshPathStatus.PathComplete,"entrance "+m.id);}
   g.level.transform.Find("Breach intact").gameObject.SetActive(false);yield return new WaitForSeconds(.5f);var stair=new NavMeshPath();Check(NavMesh.CalculatePath(g.Marker("enemy_0").position,g.Marker("combat_focus").position,NavMesh.AllAreas,stair)&&stair.status==NavMeshPathStatus.PathComplete,"continuous 006 stair navigation");g.level.transform.Find("Breach intact").gameObject.SetActive(true);
   Check(g.level.GetComponentsInChildren<Renderer>().All(r=>r.sharedMaterials.All(m=>m&&m.shader.name!="Hidden/InternalErrorShader")),"valid materials");
   yield return Picture("01-hall",new Vector3(0,3.1f,5),new Vector3(0,1.8f,36));yield return Picture("02-armory",new Vector3(-8,3.5f,20),new Vector3(-19,1,10));yield return Picture("03-office",new Vector3(8,3.2f,20),new Vector3(19,1,11));
   foreach(var id in new[]{"ak","sniper","grenades"})g.Interact(Item(id));Check(g.state.hasAK&&g.state.hasSniper&&g.state.armed,"AK sniper grenade loadout");Check(g.state.hasNightVision,"night vision acquired in map 2 armory");g.player.SwitchWeapon(1);Move(new Vector3(0,0,28));g.player.touchAim=true;g.player.yaw=0;g.player.pitch=0;yield return new WaitForSeconds(.7f);yield return Frame();
   var pose=g.player.visual.GetComponent<WeaponPose>();var bounds=pose.weapon.GetComponentsInChildren<Renderer>()[0].bounds;foreach(var r in pose.weapon.GetComponentsInChildren<Renderer>())bounds.Encapsulate(r.bounds);Check(bounds.size.magnitude<1.5f&&bounds.size.magnitude>.7f,"held AK uses metre scale after mesh conversion");var left=g.player.visual.GetComponentsInChildren<Transform>().First(t=>t.name=="Bip01 L Hand");Check(Vector3.Distance(pose.RightPalmPosition,pose.weapon.Find("Right grip").position)<.1f,"right hand at trigger");Check(Vector3.Distance(pose.LeftPalmPosition,pose.weapon.Find("Left grip").position)<.1f,"left hand supports foregrip");yield return Picture("04-AK-aim",g.player.transform.position+new Vector3(2,1.5f,1.2f),g.player.transform.position+Vector3.up*1.3f);
   yield return Picture("04-grip-close",g.player.transform.position+new Vector3(.85f,1.5f,.55f),g.player.transform.position+new Vector3(0,1.45f,.2f));
   g.player.crouch=true;yield return new WaitForSeconds(.4f);yield return Frame();Check((Application.isBatchMode?lastLeftGripError:Vector3.Distance(pose.LeftPalmPosition,pose.weapon.Find("Left grip").position))<.12f,"crouched rifle grip");yield return Picture("05-crouch",g.player.transform.position+new Vector3(2,1.2f,1.2f),g.player.transform.position+Vector3.up);g.player.crouch=false;g.player.SwitchWeapon(2);yield return new WaitForSeconds(.4f);Check(g.player.UsingSniper&&g.view.fieldOfView<25,"sniper optical zoom");yield return Frame();Capture("Documentation/ArmoryRevisionPreview/06-scope.png",g.view);yield return null;yield return null;yield return Picture("06-M700",g.player.transform.position+new Vector3(2,1.5f,1.2f),g.player.transform.position+Vector3.up*1.3f);
   var targetEnemy=(EnemyController)typeof(UndergroundCampaign).GetMethod("Spawn",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(g.underground,new object[]{99,false});targetEnemy.GetComponent<NavMeshAgent>().Warp(new Vector3(0,0,42));targetEnemy.stun=20;yield return null;var aimPoint=targetEnemy.transform.position+Vector3.up*1.2f;g.view.transform.SetPositionAndRotation(g.player.transform.position+Vector3.up*1.4f,Quaternion.LookRotation(aimPoint-(g.player.transform.position+Vector3.up*1.4f)));Physics.SyncTransforms();int rounds=g.state.sniperAmmo;g.player.Fire();if(targetEnemy.hp>0){Physics.Raycast(g.view.transform.position,g.view.transform.forward,out var diagnosticHit,120,~(1<<2));Debug.Log("M700 diagnostic: hp="+targetEnemy.hp+" ammo="+g.state.sniperAmmo+" before="+rounds+" ray="+(diagnosticHit.collider?diagnosticHit.collider.name:"none")+" target="+targetEnemy.transform.position);}Check(targetEnemy.hp<=0&&g.state.sniperAmmo==rounds-1,"M700 aimed shot damages target and consumes one round");
   int count=g.state.grenades;g.player.ThrowGrenade();Check(g.player.Throwing&&g.state.grenades==count&&!g.level.GetComponentInChildren<ThrownGrenade>(),"throw windup before grenade release");yield return Picture("07-throw",g.player.transform.position+new Vector3(2,1.5f,1.2f),g.player.transform.position+Vector3.up*1.3f);g.Pause();float progress=g.player.ThrowProgress;yield return new WaitForSecondsRealtime(.2f);Check(Mathf.Approximately(progress,g.player.ThrowProgress),"pause freezes throw animation");g.Resume();while(g.player.ThrowProgress<.56f)yield return null;Check(g.state.grenades==count-1&&g.level.GetComponentInChildren<ThrownGrenade>(),"grenade released during forward swing");yield return new WaitForSeconds(.6f);Check(!g.player.Throwing,"throw recovers");
   g.state.checkpoint=1;g.state.hp=5;g.LoadWorld(1);yield return null;Check(g.state.hp==100&&Vector3.Distance(g.player.transform.position,g.Marker("combat_spawn").position)<1,"retry restores health in protected armory");yield return new WaitForSeconds(4);Check(g.enemies.Count==0&&g.state.hp==100,"retry preparation interval");
   g.state.checkpoint=0;g.LoadWorld(1);yield return null;var method=typeof(UndergroundCampaign).GetMethod("StartFirstWave",BindingFlags.NonPublic|BindingFlags.Instance);method.Invoke(g.underground,new object[]{true});yield return new WaitForSeconds(3.5f);yield return Picture("08-breach",new Vector3(1.3f,4.3f,-5),new Vector3(0,4,-11));while(g.underground.Playing)yield return null;Check(g.enemies.Count==5,"cinematic introduces first five enemy group");
   Check(g.Running&&g.underground.VolleyActive,"player controls Alex during grenade warning");yield return new WaitForSeconds(1.8f);
   Check(g.level.GetComponentsInChildren<HostileGrenade>().Length>0&&g.enemies.All(e=>e.transform.position.z<-11),"grenades precede enemy rush");yield return Picture("15-grenade-volley",new Vector3(4,4,18),new Vector3(0,0,6));
   var liveGrenade=g.level.GetComponentInChildren<HostileGrenade>();g.Pause();var frozen=liveGrenade.transform.position;yield return new WaitForSecondsRealtime(.25f);Check(liveGrenade&&Vector3.Distance(frozen,liveGrenade.transform.position)<.001f,"pause freezes hostile grenade flight and fuse");g.Resume();
   while(g.underground.VolleyActive)yield return null;Check(g.underground.OpeningGrenadesThrown==6,"six telegraphed opening grenades");Check(g.state.hp>0&&g.state.hp<100,"opening grenades hurt exposed Alex without immediate death");yield return new WaitForSeconds(1);
   Check(CombatBrain.HitProbability(30,6.5f,false,true)<CombatBrain.HitProbability(30,0,false,true)*.5f,"sprinting still reduces hit probability while enemy accuracy increases");
   Check(g.underground.Scheduled==5,"next group does not spawn while initial group lives");Check(CombatBrain.HitProbability(30,0,false,false)>.3f,"ordinary enemy stationary hit chance increased");float beforeBurst=g.state.hp;for(int i=0;i<20;i++)g.EnemyShot(6);Check(beforeBurst-g.state.hp<=6,"simultaneous shooters cannot stack damage in one frame");g.state.hp=100;
Check(g.enemies.All(e=>e.transform.position.z>-17),"agents descend from 006 instead of teleport crowd");yield return Picture("09-first-group",new Vector3(4,3,7),new Vector3(0,1,0));
   var shooter=g.enemies[0];foreach(var e in g.enemies.Skip(1))e.gameObject.SetActive(false);shooter.GetComponent<NavMeshAgent>().Warp(new Vector3(0,0,10));shooter.speed=0;Move(new Vector3(0,0,55));float health=g.state.hp;UnityEngine.Random.InitState(71);float sightUntil=Time.time+9;bool sawDistant=false;while(Time.time<sightUntil){sawDistant|=shooter.tactical.CanSeePlayer;yield return null;}Check(sawDistant,"enemy sees exposed player at 45 metres");Check(g.state.hp<health,"exposed distant player actually takes damage");foreach(var grenade in g.level.GetComponentsInChildren<HostileGrenade>())Destroy(grenade.gameObject);typeof(UndergroundCampaign).GetField("nextGrenade",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(g.underground,Time.time+30);var shield=GameObject.CreatePrimitive(PrimitiveType.Cube);shield.transform.position=new Vector3(0,1.5f,50);shield.transform.localScale=new Vector3(6,3,1);float coveredHealth=g.state.hp;yield return new WaitForSeconds(2);Check(g.state.hp==coveredHealth,"solid cover prevents enemy bullet damage");Destroy(shield);g.state.hp=100;
   shooter.TakeDamage(1000);yield return new WaitForSeconds(.7f);float lowest=float.PositiveInfinity;var corpseMesh=new Mesh();foreach(var skin in shooter.GetComponentsInChildren<SkinnedMeshRenderer>()){skin.BakeMesh(corpseMesh);foreach(var v in corpseMesh.vertices)lowest=Mathf.Min(lowest,skin.transform.TransformPoint(v).y);}Destroy(corpseMesh);Check(lowest>=-.025f&&lowest<.08f,"corpse mesh settles against floor");yield return Picture("13-grounded-body",shooter.transform.position+new Vector3(2,1.5f,2),shooter.transform.position+new Vector3(-.6f,.2f,0));
   foreach(var e in g.enemies)e.gameObject.SetActive(true);int countBefore=g.state.kills;HostileGrenade.Launch(g,new Vector3(0,2,30),new Vector3(0,0,30));while(g.underground.State==UndergroundCampaign.Encounter.FirstWave){foreach(var e in g.enemies.ToArray())if(e&&e.hp>0)e.TakeDamage(1000);typeof(UndergroundCampaign).GetField("spawnClock",BindingFlags.NonPublic|BindingFlags.Instance).SetValue(g.underground,0f);yield return null;}
   yield return null;Check(g.level.GetComponentsInChildren<HostileGrenade>().Length==0,"resupply clears remaining hostile grenades");Check(g.underground.Scheduled==30&&g.underground.State==UndergroundCampaign.Encounter.Resupply,"resupply follows exactly thirty kills");Check(g.underground.RestRemaining>40&&g.Running,"forty five second playable loot break");Check(g.level.GetComponentsInChildren<Interaction>().Count(i=>i.id.StartsWith("corpse_loot_"))==30,"thirty corpse loot drops");g.state.hp=40;var supply=g.level.GetComponentsInChildren<Interaction>().First(i=>i.id.StartsWith("corpse_loot_"));Move(supply.transform.position+Vector3.back);Physics.SyncTransforms();g.player.FindTarget();Check(g.player.target&&g.player.target.id.StartsWith("corpse_loot_"),"corpse loot is reachable through normal interaction targeting");g.Interact(supply);Check(g.state.corpseLoot.Count==29,"collected loot is removed from saved drop list");Check(g.state.hp>40,"healing loot available during break");Check(g.HasSave(),"resupply checkpoint is accepted by save loader");g.Continue();yield return null;Check(g.underground.State==UndergroundCampaign.Encounter.Resupply&&g.level.GetComponentsInChildren<Interaction>().Count(i=>i.id.StartsWith("corpse_loot_"))==29,"continue restores only uncollected corpse loot");typeof(UndergroundCampaign).GetProperty("RestRemaining").SetValue(g.underground,.01f);yield return null;yield return null;bool repeatedExplosion=false;while(g.underground.Playing){repeatedExplosion|=FindObjectsByType<BlastEffects>(FindObjectsSortMode.None).Length>0;yield return null;}
   Check(!repeatedExplosion,"Victor arrival does not repeat door explosion");var escorts=g.enemies.Where(e=>e&&e.hp>0&&!e.boss).ToArray();var boss=g.enemies.First(e=>e&&e.boss&&e.hp>0);Check(escorts.Length==20&&g.underground.Scheduled==20,"twenty escorts plus Victor");Check(escorts.All(e=>e.transform.position.z>boss.transform.position.z),"Victor follows behind all twenty escorts");Check(g.underground.State==UndergroundCampaign.Encounter.Retreat&&Item("retreat").Available,"retreat instruction opens immediately after suppression arrival");yield return Picture("14-reinforcements",new Vector3(4,3,8),new Vector3(0,2,-7));
   Check(escorts.All(e=>e.elite&&e.maxHp==140),"Victor escorts have stronger elite loadout");foreach(var e in escorts.Take(10))e.TakeDamage(1000);Check(g.underground.Overwhelming,"ten escort kills activate overwhelming pressure");Move(new Vector3(-17,0,18));g.state.hp=50;Check(!g.underground.TryEmergencyRetreat(),"exactly fifty HP does not trigger retreat");g.state.hp=100;foreach(var e in g.enemies.Where(e=>e&&e.hp>0))e.stun=30;float forceDeadline=Time.time+12;while(!g.underground.AutoRetreat&&Time.time<forceDeadline)yield return null;Check(g.underground.AutoRetreat&&g.underground.Playing&&g.state.hp<50,"overwhelming pressure guarantees retreat even if player holds cover");float protectedHealth=g.state.hp;g.Damage(1000);Check(g.state.hp==protectedHealth,"incoming damage cannot kill during retreat cinematic");yield return null;yield return Frame();Check(g.view.transform.position.y>g.player.transform.position.y+3,"retreat camera rises above Alex");Capture("Documentation/ArmoryRevisionPreview/16-auto-retreat.png",g.view);yield return null;Check(g.enemies.Where(e=>e&&e.hp>0).All(e=>e.GetComponent<NavMeshAgent>().speed>=4.6f),"pursuers run during automatic retreat");
   g.Pause();var retreatPosition=g.player.transform.position;yield return new WaitForSecondsRealtime(.25f);Check(Vector3.Distance(retreatPosition,g.player.transform.position)<.001f,"pause freezes automatic retreat");g.Resume();
   float retreatDeadline=Time.time+30;while(g.state.stage==1&&Time.time<retreatDeadline)yield return null;Check(g.state.stage==2&&g.state.hp>0,"automatic retreat navigates out of armory room and loads map 3 alive");while(g.underground.Playing)yield return null;Check(g.Running&&!DescentBlackout.Visible,"map 3 restores control after center arrival");
   g.state=new CampaignSave{stage=0,keycard=true,introCompleted=true};g.LoadWorld(0);yield return null;var desktop=g.level.GetComponentsInChildren<Transform>().FirstOrDefault(t=>t.name.StartsWith("Desktop computer")&&t.position.z>25&&t.position.x<-8);Check(desktop&&desktop.Find("Screen faces operator +Z")&&desktop.Find("Keyboard")&&desktop.Find("PC tower"),"Marcus desktop has screen keyboard tower");if(desktop)yield return Picture("10-Marcus",desktop.position+new Vector3(1,1.2f,2),desktop.position+Vector3.up*.3f);
   Check(!g.level.GetComponentsInChildren<Transform>().Any(t=>t.name=="Lối tối xuống B1"),"removed separate black portal plane");
   g.flags.Add("computer");typeof(OpeningSequence).GetProperty("PursuitStarted").SetValue(g.opening,true);var air=g.airlock;Move(air.transform.position-Vector3.forward);air.UnlockOuter();while(air.OuterMoving)yield return null;Move(air.transform.TransformPoint(new Vector3(0,0,1.9f)));air.StartScan();while(!air.AutoDescending)yield return null;
   var fade=air.GetComponent<DescentBlackout>();while(fade.opacity<1)yield return null;Time.timeScale=0;yield return Frame();if(!Application.isBatchMode)ScreenCapture.CaptureScreenshot("Documentation/ArmoryRevisionPreview/11-black-cut.png");yield return null;yield return null;
   if(Application.isBatchMode)Check(fade.opacity==1,"full blackout before scene replacement (headless)");else{var image=new Texture2D(2,2);image.LoadImage(File.ReadAllBytes("Documentation/ArmoryRevisionPreview/11-black-cut.png"));Check(image.GetPixels32().All(p=>p.r<4&&p.g<4&&p.b<4),"single fullscreen black transition covers HUD");Destroy(image);}Time.timeScale=1;while(g.state.stage==0)yield return null;Check(g.GetComponent<DescentBlackout>()&&g.GetComponent<DescentBlackout>().opacity>.5f,"black overlay survives level replacement");yield return new WaitForSeconds(1.1f);Check(!g.GetComponent<DescentBlackout>()&&g.Running,"map 2 reveals and restores control");Finish();
  }
  void LateUpdate(){if(g&&g.player&&g.player.visual){var pose=g.player.visual.GetComponent<WeaponPose>();if(pose&&pose.weapon&&pose.weapon.Find("Left grip"))lastLeftGripError=Vector3.Distance(pose.LeftPalmPosition,pose.weapon.Find("Left grip").position);}if(captureCamera&&capturePath!=null){ControlRevisionSelfTest.Capture(captureCamera,capturePath);capturePath=null;captureCamera=null;}}
  void Update(){if(!done&&deadline>0&&Time.realtimeSinceStartup>deadline){Check(false,"timeout");Finish();}}
  void Finish(){done=true;log.Add("RESULT "+failures+" failures");File.WriteAllLines("Documentation/armory-revision-test.txt",log);
#if UNITY_EDITOR
   UnityEditor.EditorApplication.Exit(failures==0?0:1);
#endif
  }
 }
}
