using UnityEngine;
namespace BlackMarket {
 public class BlastEffects:MonoBehaviour {
  float life=4;Light flash;static Material smoke;
  static Material Smoke(){if(smoke)return smoke;var texture=new Texture2D(32,32,TextureFormat.RGBA32,false);for(int y=0;y<32;y++)for(int x=0;x<32;x++){float a=Mathf.Clamp01(1-Vector2.Distance(new Vector2(x,y),new Vector2(15.5f,15.5f))/15.5f);texture.SetPixel(x,y,new Color(1,1,1,a*a));}texture.Apply();smoke=new Material(Shader.Find("Universal Render Pipeline/Particles/Unlit"));smoke.SetTexture("_BaseMap",texture);smoke.SetColor("_BaseColor",Color.white);smoke.SetFloat("_Surface",1);smoke.SetFloat("_Blend",0);smoke.SetFloat("_SrcBlend",5);smoke.SetFloat("_DstBlend",10);smoke.SetFloat("_ZWrite",0);smoke.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");smoke.renderQueue=3000;return smoke;}

  public static void Explode(Vector3 position,float radius){var go=new GameObject("Vụ nổ / khói");go.transform.position=position;var fx=go.AddComponent<BlastEffects>();fx.flash=go.AddComponent<Light>();fx.flash.color=new Color(1,.35f,.06f);fx.flash.range=radius*3;fx.flash.intensity=70;var ps=go.AddComponent<ParticleSystem>();ps.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);var m=ps.main;m.loop=false;m.duration=.3f;m.startLifetime=new ParticleSystem.MinMaxCurve(1,3);m.startSpeed=new ParticleSystem.MinMaxCurve(radius*.3f,radius);m.startSize=new ParticleSystem.MinMaxCurve(.3f,1.2f);m.startColor=new Color(.8f,.32f,.08f,.7f);m.maxParticles=70;var em=ps.emission;em.rateOverTime=0;em.SetBursts(new[]{new ParticleSystem.Burst(0,65)});var shape=ps.shape;shape.shapeType=ParticleSystemShapeType.Sphere;shape.radius=.2f;var color=ps.colorOverLifetime;color.enabled=true;var gradient=new Gradient();gradient.SetKeys(new[]{new GradientColorKey(new Color(1,.6f,.1f),0),new GradientColorKey(new Color(.12f,.13f,.14f),.25f),new GradientColorKey(new Color(.15f,.16f,.17f),1)},new[]{new GradientAlphaKey(.9f,0),new GradientAlphaKey(.6f,.6f),new GradientAlphaKey(0,1)});color.color=gradient;var size=ps.sizeOverLifetime;size.enabled=true;size.size=new ParticleSystem.MinMaxCurve(1,AnimationCurve.Linear(0,.4f,1,3));ps.GetComponent<ParticleSystemRenderer>().sharedMaterial=Smoke();ps.Play();}
  void Update(){life-=Time.deltaTime;flash.intensity=Mathf.Max(0,flash.intensity-Time.deltaTime*130);if(life<=0)Destroy(gameObject);}
 }
}
