using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEngine.AI;
namespace BlackMarket {
 public class MissionFlowSelfTest:MonoBehaviour {
  Campaign game;readonly List<string> report=new List<string>();int failures;float deadline;bool visual;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Launch(){var args=Environment.GetCommandLineArgs();if(Debug.isDebugBuild && (Array.IndexOf(args,"--mission-check")>=0||Array.IndexOf(args,"--revision-check")>=0))new GameObject("Revision QA").AddComponent<MissionFlowSelfTest>();}
  void Check(bool value,string text){report.Add((value?"PASS ":"FAIL ")+text);Debug.Log(report.Last());if(!value)failures++;}
  Interaction Item(string id)=>game.level.GetComponentsInChildren<Interaction>(true).Single(i=>i.id==id);
  void Teleport(Vector3 p){game.player.body.enabled=false;game.player.transform.position=p;game.player.body.enabled=true;Physics.SyncTransforms();}
  IEnumerator Shot(string name){if(!visual)yield break;yield return null;yield return null;ScreenCapture.CaptureScreenshot("Documentation/RevisionPreview/"+name+".png");yield return null;yield return null;}
  IEnumerator Read(){MissionTestSteps.SkipIntro(game);while(game.ui.modal=="story"){if(game.ui.ComputerScreen){if(game.ui.TerminalPageReady)game.ui.NextTerminalPage();}else if(game.ui.StoryReady)game.ui.ContinueStory();yield return null;}}
  IEnumerator Start(){
   deadline=Time.realtimeSinceStartup+360;visual=!Application.isBatchMode;Directory.CreateDirectory("Documentation/RevisionPreview");Application.runInBackground=true;yield return null;game=Campaign.Instance;if(Array.IndexOf(Environment.GetCommandLineArgs(),"--revision-shots")>=0){yield return Retake();Finish();yield break;}File.Delete(game.SavePath+".reading");game.LoadWorld(0);
   game.ui.Story("KIỂM TRA NHỊP ĐỌC","Xin chào Alex.",null,"revision-timing");Check(!game.ui.TextComplete && !game.ui.StoryReady,"story begins with typewriter and disabled continue");while(!game.ui.TextComplete)yield return null;float finished=Time.realtimeSinceStartup;Check(!game.ui.StoryReady,"button waits after final character");yield return new WaitForSecondsRealtime(2.7f);Check(!game.ui.StoryReady,"button still gated before three seconds");while(!game.ui.StoryReady)yield return null;Check(Time.realtimeSinceStartup-finished<3.25f,"continue lights at three seconds after final character");game.ui.ContinueStory();
   Check(game.player.visual.GetComponentsInChildren<SkinnedMeshRenderer>().Any(r=>r.sharedMesh && r.sharedMesh.name.Contains("m014")),"young protagonist mesh imported");
   var drawers=game.level.GetComponentsInChildren<OfficeDrawer>().OrderBy(d=>d.number).ToArray();Check(drawers.Length==24 && drawers.Count(d=>d.redCard)==1,"six cabinets, 24 drawers, one red card");Check(drawers.Select(d=>d.transform.parent).Distinct().All(t=>Mathf.Abs(t.position.x+5.6f)<.1f||Mathf.Abs(t.position.x+13.4f)<.1f),"all search cabinets placed against office walls");
   Check(game.level.GetComponentsInChildren<Transform>().Count(t=>t.name.StartsWith("Giá kho "))==36,"warehouse has four times nine original racks");Check(game.airlock.transform.position.z==47.8f,"warehouse depth increased from six to eighteen metres");
   Item("computer").Use();Check(game.ui.modal=="","computer rejects missing card");Check(!Item("keycard").Available,"card hidden before drawer opens");foreach(var d in game.level.GetComponentsInChildren<RoomDoor>())d.SetOpenImmediate(true);
   if(visual){game.player.enabled=false;game.view.transform.position=new Vector3(-9,3.1f,22.4f);game.view.transform.LookAt(new Vector3(-9.5f,1,27));yield return Shot("01-office");game.player.enabled=true;}
   foreach(var d in drawers){var spot=d.transform.position-d.transform.forward*1.1f;spot.y=.05f;Teleport(spot);game.player.FindTarget();Check(game.player.target==d.GetComponent<Interaction>(),"drawer target "+d.number);game.player.Interact();yield return new WaitForSeconds(.7f);if(d.redCard){game.player.FindTarget();Check(game.player.target==Item("keycard"),"red card can be picked up separately");game.player.Interact();}}
   Check(game.state.keycard && drawers.All(d=>d.Revealed),"search and card collection complete");Teleport(new Vector3(-9,0,26));Item("computer").Use();yield return Shot("02-desktop");Check(game.ui.modal=="computer","desktop awaits file click");var rect=game.ui.OrderFileRect;game.ui.ProcessMenuPointer(rect.center,true,false);game.ui.ProcessMenuPointer(rect.center,false,true);if(!visual)game.ui.TryOpenOrderFile();yield return null;yield return null;Check(game.ui.ComputerScreen,"Order 71 icon opens document");while(!game.ui.TextComplete)yield return null;Check(!game.ui.TerminalPageReady,"terminal also waits three seconds after typing");yield return new WaitForSecondsRealtime(3.1f);Check(game.ui.TerminalPageReady,"terminal next button enabled after three seconds");yield return Shot("03-document");yield return Read();
   Check(game.opening.Playing,"reading starts convoy");yield return new WaitForSeconds(2);yield return Shot("04-car-arrival");yield return new WaitForSeconds(5);yield return Shot("05-vest-group");while(game.opening.Playing)yield return null;Check(game.enemies.Count==4,"four members of suited group");
   if(visual){game.player.enabled=false;game.view.transform.position=new Vector3(11,3.3f,31);game.view.transform.LookAt(new Vector3(-8,1,41));yield return Shot("06-warehouse");game.player.enabled=true;}
   yield return Walk(Item("door06").transform.position);Check(game.state.hp>0,"larger winding warehouse escape survivable");if(!game.Running){Finish();yield break;}Item("door06").Use();var air=game.airlock;while(air.OuterMoving)yield return null;Check(game.state.stage==0,"outer card gate does not advance stage");yield return Walk(air.transform.TransformPoint(new Vector3(.9f,0,2.7f)));
   air.StartScan();Check(air.Scanning && !game.Running,"scan locks controls from far edge of pad");while(air.ScanProgress<.25f)yield return null;var face=game.player.transform.position+Vector3.up*1.62f;Check(!Physics.Linecast(game.view.transform.position,face,~(1<<2),QueryTriggerInteraction.Ignore),"scan camera has unobstructed view of face");Check(Vector3.Distance(game.player.transform.position,air.transform.TransformPoint(new Vector3(0,0,1.65f)))<.03f,"scan aligns Alex to safe pad");yield return Shot("07-face-scan");game.Pause();float progress=air.ScanProgress;yield return new WaitForSecondsRealtime(.3f);Check(air.ScanProgress==progress,"scan pauses correctly");game.Resume();while(!air.AutoDescending)yield return null;Check(air.FaceVerified && !game.Running,"descent starts without restoring player input");while(game.state.stage==0 && game.player.transform.position.y>-.5f)yield return null;Check(game.state.stage==0 && !game.Running,"Alex runs down real stairs before loading B1");yield return Shot("08-auto-stairs");while(game.state.stage==0)yield return null;Check(game.state.stage==1 && game.Running,"automatic staircase sequence loads B1 and restores control");
   game.NewGame();yield return Read();Check(game.level.GetComponentsInChildren<OfficeDrawer>().All(d=>!d.IsOpen) && !game.airlock.OuterUnlocked,"new game resets cabinets and gates");game.state.keycard=true;Item("computer").Use();game.ui.OpenOrderFile();Check(game.ui.StoryReady,"completed file skippable on replay");game.ui.SkipReadStory();game.opening.Skip();yield return null;yield return null;Check(game.opening.PursuitStarted,"skip still starts suited group encounter");Finish();
  }
  IEnumerator Retake(){
   game.LoadWorld(0);game.state.keycard=true;game.flags.Add("computer");game.MarkStorySeen("arrival");game.opening.Begin();yield return new WaitForSeconds(2);yield return Shot("04-car-arrival");yield return new WaitForSeconds(5);yield return Shot("05-vest-group");game.opening.Skip();while(game.opening.Playing)yield return null;
   var air=game.airlock;Teleport(air.transform.position+new Vector3(0,0,-1.1f));air.UnlockOuter();while(air.OuterMoving)yield return null;Teleport(air.transform.TransformPoint(new Vector3(.9f,0,2.7f)));air.StartScan();yield return null;Check(!Physics.Linecast(game.view.transform.position,game.player.transform.position+Vector3.up*1.62f,~(1<<2),QueryTriggerInteraction.Ignore),"face visible immediately when scan begins");while(air.ScanProgress<.3f)yield return null;yield return Shot("07-face-scan");while(!air.AutoDescending)yield return null;while(game.player.transform.position.y>-.9f)yield return null;yield return Shot("08-auto-stairs");while(game.state.stage==0)yield return null;Check(game.state.stage==1,"revised staircase completes");
  }
  IEnumerator Walk(Vector3 goal){
   yield return new WaitForSeconds(.3f);var p=game.player;var path=new NavMeshPath();bool ok=NavMesh.SamplePosition(p.transform.position,out var start,2,-1)&&NavMesh.SamplePosition(goal,out var end,2,-1)&&NavMesh.CalculatePath(start.position,end.position,-1,path)&&path.status==NavMeshPathStatus.PathComplete;Check(ok,"navigation reaches "+goal);if(!ok)yield break;float length=0;for(int i=1;i<path.corners.Length;i++)length+=Vector3.Distance(path.corners[i-1],path.corners[i]);if(goal.z>45 && goal.z<48)Check(length>65,"warehouse path bends through several rack rows: "+length.ToString("F1")+"m");p.enabled=false;
   foreach(var corner in path.corners){float until=Time.time+10;while(game.Running && Time.time<until && Vector2.Distance(new Vector2(p.transform.position.x,p.transform.position.z),new Vector2(corner.x,corner.z))>.16f){var d=corner-p.transform.position;d.y=0;p.body.Move(Vector3.ClampMagnitude(d.normalized*6.5f*Time.deltaTime,d.magnitude)+Vector3.down*8*Time.deltaTime);yield return null;}}
   Check(Vector2.Distance(new Vector2(p.transform.position.x,p.transform.position.z),new Vector2(goal.x,goal.z))<1.2f,"CharacterController physically traverses route");p.enabled=true;
  }
  void Update(){if(deadline>0 && Time.realtimeSinceStartup>deadline){Check(false,"deadline");Finish();}}
  void Finish(){enabled=false;report.Add("RESULT "+failures+" failures");File.WriteAllLines(Array.IndexOf(Environment.GetCommandLineArgs(),"--revision-shots")>=0?"Documentation/revision-shots-test.txt":visual?"Documentation/revision-ui-test.txt":"Documentation/revision-runtime-test.txt",report);
#if UNITY_EDITOR
   UnityEditor.EditorApplication.Exit(failures==0?0:1);
#else
   Application.Quit(failures==0?0:1);
#endif
  }
 }
}
