using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using UnityEngine;
using UnityEngine.AI;
namespace BlackMarket {
 public class UndergroundSelfTest:MonoBehaviour {
  Campaign g;List<string> report=new List<string>();int failures;float deadline;bool done;float logAt;bool finalOnly,endingOnly;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Launch(){if(Debug.isDebugBuild&&(Array.IndexOf(Environment.GetCommandLineArgs(),"--campaign-v2-check")>=0||Array.IndexOf(Environment.GetCommandLineArgs(),"--ending-check")>=0))new GameObject("Campaign v2 QA").AddComponent<UndergroundSelfTest>();}
  void Check(bool ok,string message){report.Add((ok?"PASS ":"FAIL ")+message);Debug.Log(report.Last());if(!ok)failures++;}
  Interaction Item(string id)=>g.level.GetComponentsInChildren<Interaction>(true).First(x=>x.id==id);
  void Use(string id){g.Interact(Item(id));}
  void Move(Vector3 p){g.player.body.enabled=false;g.player.transform.position=p;g.player.body.enabled=true;}
  IEnumerator Shot(string name){yield return null;yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot("Documentation/UndergroundPreview/"+name+".png");yield return null;yield return null;}
  void Invoke(string method,params object[] args)=>typeof(UndergroundCampaign).GetMethod(method,BindingFlags.Instance|BindingFlags.NonPublic).Invoke(g.underground,args);
  IEnumerator Drain(){while(g.ui.modal=="story"){if(g.ui.ComputerScreen&&g.ui.TerminalPageReady)g.ui.NextTerminalPage();else if(!g.ui.ComputerScreen&&g.ui.StoryReady)g.ui.ContinueStory();yield return null;}}
  IEnumerator Start(){
   Application.runInBackground=true;finalOnly=Array.IndexOf(Environment.GetCommandLineArgs(),"--final-visual")>=0;deadline=Time.realtimeSinceStartup+900;Directory.CreateDirectory("Documentation/UndergroundPreview");yield return null;g=Campaign.Instance;endingOnly=Array.IndexOf(Environment.GetCommandLineArgs(),"--ending-check")>=0;if(endingOnly){g.state=new CampaignSave{stage=2,checkpoint=4,keycard=true,codeRecovered=true,hasAK=true,armed=true,hasNightVision=true};g.LoadWorld(2);yield return null;g.underground.ReadFinal();g.MarkStorySeen("final-file-v2");g.ui.SkipReadStory();Check(g.state.evidenceCopied&&g.underground.EscapeRemaining>89,"ending starts only after evidence transfer");Use("escape");yield return new WaitForSeconds(8);yield return Shot("10-motorcycle-ending");yield return new WaitForSeconds(6);yield return Shot("11-explosion");yield return new WaitForSeconds(1.6f);yield return Shot("12-rubble");while(g.underground.Playing)yield return null;Check(g.state.campaignComplete&&g.ui.modal=="story","ending completes after explosion");yield return Shot("13-final-ending");Finish();yield break;}

   Check(StoryData.Worlds.Length==3&&StoryData.UnlockCode.Length==10,"three worlds and ten-digit code");Check(StoryData.Terminal.Contains("ĐÃ KHÓA")&&StoryData.FinalFile.Contains("Marcus"),"locked opening and final evidence exist");
   if(File.Exists(g.SavePath+".reading"))File.Delete(g.SavePath+".reading");if(!finalOnly){g.state=new CampaignSave{stage=1,keycard=true,introCompleted=true};g.LoadWorld(1);yield return null;Check(g.underground.State==UndergroundCampaign.Encounter.Equip,"armory starts at equipment objective");
   Check(g.level.GetComponentsInChildren<Renderer>().All(r=>r.sharedMaterials.All(m=>m&&m.shader.name!="Hidden/InternalErrorShader")),"armory materials valid");
   foreach(string id in new[]{"pistol","ak","grenades","base_computer","retreat"}){var path=new NavMeshPath();bool valid=NavMesh.CalculatePath(g.Marker("spawn").position,Item(id).transform.position,NavMesh.AllAreas,path);Check(valid&&path.status==NavMeshPathStatus.PathComplete,"walkable route to "+id);}
   yield return Shot("01-armory");Use("base_computer");Check(g.ui.modal==""&&g.underground.State==UndergroundCampaign.Encounter.Equip,"computer requires full equipment");Use("pistol");Use("ak");Use("grenades");Check(g.state.armed&&g.state.hasAK&&g.state.grenades==4,"all weapons and grenade kit acquired");
   Use("base_computer");Check(g.ui.ComputerScreen&&!g.ui.TerminalPageReady,"first document types before next enabled");float hp=g.state.hp;g.EnemyShot(6);Check(g.state.hp==hp,"documents suspend player damage");yield return Shot("02-base-file");g.MarkStorySeen("base-file-v2");g.ui.SkipReadStory();Check(g.underground.Playing,"alarm triggers breach cinematic");g.Pause();yield return new WaitForSecondsRealtime(.2f);Check(g.underground.Playing&&!g.Running,"pause locks breach");g.Resume();yield return new WaitForSeconds(3);yield return Shot("03-breach");while(g.underground.Playing)yield return null;
   int guard=0;while(g.underground.State==UndergroundCampaign.Encounter.FirstWave&&guard++<4000){foreach(var e in g.enemies.ToArray())if(e&&e.hp>0)e.TakeDamage(1000);yield return null;}Check(g.state.kills==10&&g.ui.modal=="story","first wave exactly ten defeated before reflection");g.MarkStorySeen("after-first-wave-v2");g.ui.SkipReadStory();while(g.underground.Playing)yield return null;Check(g.underground.State==UndergroundCampaign.Encounter.Assault&&g.enemies.Any(e=>e&&e.boss&&e.hp>0),"Victor reinforcement assault starts");
   g.state.hp=49;yield return null;Check(g.underground.State==UndergroundCampaign.Encounter.Retreat&&Item("retreat").Available,"health threshold enables retreat");g.state.hp=100;var man=g.enemies.FirstOrDefault(e=>e&&e.combat&&!e.boss&&e.hp>0);if(man){int id=man.combatId;man.TakeDamage(1000);Check((g.state.reinforcementDeaths&(1<<id))!=0,"reinforcement death persists");}
   Use("retreat");while(g.state.stage==1)yield return null;yield return null;Check(g.state.stage==2&&g.underground.State==UndergroundCampaign.Encounter.ControlPrep,"automatic descent loads control center");
   }else{
    g.state=new CampaignSave{version=1,stage=4,keycard=true,armed=true,hasAK=true};g.Save();g.Continue();yield return null;Check(g.state.version==2&&g.state.stage==1&&!g.state.armed,"old save migrates safely to new armory");yield return Shot("01-armory");
    g.state=new CampaignSave{stage=1,checkpoint=2,keycard=true,armed=true,hasAK=true,hp=100};g.LoadWorld(1);foreach(var enemy in g.enemies)enemy.stun=10;yield return null;typeof(UndergroundCampaign).GetField("waveClock",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(g.underground,35f);yield return null;Check(g.underground.State==UndergroundCampaign.Encounter.Retreat&&g.state.hp>=50,"unhurt player receives timed retreat after 35 seconds");Move(new Vector3(0,0,60));Use("retreat");while(g.state.stage==1)yield return null;Check(g.state.stage==2&&g.Running,"retreat stair fade loads control center");
    g.state=new CampaignSave{stage=2,checkpoint=3,keycard=true,armed=true,hasAK=true,hasNightVision=true,lightsDestroyed=true};g.Save();g.Continue();yield return null;Check(g.underground.Dark&&!g.level.transform.Find("Control gate").gameObject.activeSelf&&!g.level.transform.Find("Breach intact").gameObject.activeSelf,"final checkpoint reload preserves blackout and open entry");
    g.state=new CampaignSave{stage=2,keycard=true,introCompleted=true,armed=true,hasAK=true,selectedWeapon=1,rifleAmmo=30,rifleReserve=300};g.LoadWorld(2);yield return null;}
   foreach(string id in new[]{"medical","nightvision","control_entry","breaker","final_terminal","escape"}){var path=new NavMeshPath();var origin=(id=="medical"||id=="nightvision"||id=="control_entry")?g.Marker("spawn").position:new Vector3(0,0,16);bool valid=NavMesh.CalculatePath(origin,Item(id).transform.position,NavMesh.AllAreas,path);Check(valid&&path.status==NavMeshPathStatus.PathComplete,"control route to "+id);}
   Use("medical");Use("nightvision");Check(g.state.hp==100&&g.state.hasNightVision&&g.player.nightVision.Active,"safe prep heals and equips night vision");g.player.nightVision.Toggle();yield return Shot("04-control-prep");Use("control_entry");while(g.underground.Playing)yield return null;Move(new Vector3(0,0,34));foreach(var e in g.enemies)if(e&&e.boss)e.stun=12;g.ui.hurt=0;yield return null;yield return Shot("05-control-lit");var breaker=g.level.GetComponentInChildren<LightingBreaker>();breaker.Hit(60);Check(g.underground.Dark,"shooting breaker cuts light power");g.player.yaw=180;yield return Shot("06-blackout");g.player.nightVision.Toggle();yield return null;yield return Shot("07-nightvision");Check(g.enemies.Where(e=>e&&e.hp>0&&!e.nightSight).All(e=>!e.tactical.CanSeePlayer),"non-NV enemies lose sight in darkness");Check(g.enemies.Any(e=>e&&e.boss&&e.nightSight),"Victor has night vision");
   float hpFinal=g.state.hp;g.EnemyShot(6);Check(Mathf.Approximately(hpFinal-g.state.hp,6),"weapon damage is real damage, no old two-hit override");g.state.hp=100;
   int grenades=g.state.grenades;g.player.ThrowGrenade();Check(g.state.grenades==grenades-1,"grenade uses inventory");g.Pause();yield return new WaitForSecondsRealtime(2.1f);Check(g.level.GetComponentInChildren<ThrownGrenade>(),"grenade fuse freezes while paused");g.Resume();yield return new WaitForSeconds(2.2f);Check(!g.level.GetComponentInChildren<ThrownGrenade>(),"grenade explodes after fuse");g.state.hp=100;
   int finalGuard=0;while(g.underground.State==UndergroundCampaign.Encounter.FinalBattle&&finalGuard++<5000){foreach(var e in g.enemies.ToArray())if(e&&e.hp>0)e.TakeDamage(1000);g.state.hp=100;yield return null;}Check(g.underground.State==UndergroundCampaign.Encounter.Decrypt,"final victory unlocks terminal");Check(g.underground.Scheduled==15,"final schedules only fifteen reinforcement IDs");Use("final_terminal");Check(g.state.codeRecovered&&g.ui.modal=="decoder","central server retrieves code");yield return Shot("08-decoder");g.underground.ReadFinal();Check(g.ui.ComputerScreen&&g.underground.EscapeRemaining==0,"final file opens before escape countdown");yield return new WaitForSecondsRealtime(2);yield return Shot("09-final-file");g.MarkStorySeen("final-file-v2");g.ui.SkipReadStory();Check(g.state.evidenceCopied&&g.underground.State==UndergroundCampaign.Encounter.Escape&&g.underground.EscapeRemaining>89,"copy evidence then start escape timer");Use("escape");yield return new WaitForSeconds(8);yield return Shot("10-motorcycle-ending");yield return new WaitForSeconds(6);yield return Shot("11-explosion");while(g.underground.Playing)yield return null;Check(g.state.campaignComplete&&g.state.checkpoint==5&&g.ui.modal=="story","canonical ending completed and saved");g.Continue();Check(g.ui.modal=="story"&&g.state.campaignComplete,"completed save returns to ending without replaying battle");yield return Shot("11-ending");Finish();
  }
  void Update(){if(g&&Time.realtimeSinceStartup>logAt){logAt=Time.realtimeSinceStartup+10;Debug.Log("QA STATE "+g.ui.modal+" active="+g.active+" scale="+Time.timeScale+" playing="+(g.underground&&g.underground.Playing)+" state="+g.underground?.State+" hp="+g.state.hp);}if(!done&&deadline>0&&Time.realtimeSinceStartup>deadline){Check(false,"test timeout");Finish();}}
  void Finish(){done=true;report.Add("RESULT "+failures+" failures");File.WriteAllLines(endingOnly?"Documentation/underground-ending-test.txt":finalOnly?"Documentation/underground-final-test.txt":"Documentation/underground-test.txt",report);
#if UNITY_EDITOR
   UnityEditor.EditorApplication.Exit(failures==0?0:1);
#else
   Application.Quit(failures==0?0:1);
#endif
  }
 }
}
